1. Import numpy as np and see the version

In [6]:
import numpy as np
print np.__version__

1.9.2


2. How to create a 1D array?

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

3. How to create a boolean array?

arr = np.full((3,3),1,dtype=bool)
arr

4. How to extract items that satisfy a given condition from 1D array?

In [11]:
arr = np.arange(2,13)
arr[arr % 2 == 1]

array([ 3,  5,  7,  9, 11])

In [12]:
np.where(arr%2==1)

(array([1, 3, 5, 7, 9]),)

5. How to replace items that satisfy a condition with another value in numpy array?

In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6. How to replace items that satisfy a condition without affecting the original array?

In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr%2==1, -1, arr)
print out
print arr

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


7. How to reshape an array?

In [22]:
np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to stack two arrays vertically?

In [26]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
arr = np.vstack([a,b])
arr1 = np.concatenate([a,b], axis=0)
print arr,'\n', arr1

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]] 
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


9. How to stack two arrays horizontally?

In [27]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
arr = np.hstack([a,b])
arr1 = np.concatenate([a,b], axis=1)
print arr,'\n', arr1

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]] 
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


 10. How to generate custom sequences in numpy without hardcoding?

In [28]:
a = np.array([1,2,3])
b = np.tile(a,3)
c = np.repeat(a,3)
d = np.concatenate([b,c], axis=1)
print d

[1 2 3 1 2 3 1 2 3 1 1 1 2 2 2 3 3 3]


11. How to get the common items between two python numpy arrays?

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
arr = np.intersect1d(a,b)
print arr

[2 4]


12. How to remove from one array those items that exist in another?

In [32]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

13. How to get the positions where elements of two arrays match?

In [33]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

14. How to extract all numbers between a given range from a numpy array?

In [40]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
condition = np.where((a > 5) & (a < 11))
print a[condition]
b = a[(a>5) & (a<11)]
print b

[ 6  9 10]
[ 6  9 10]


15. How to make a python function that handles scalars to work on numpy arrays?

In [42]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    
vmaxx = np.vectorize(maxx)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
vmaxx(a, b)

array([6, 7, 9, 8, 9, 7, 5])

16. How to swap two columns in a 2d numpy array?

In [44]:
arr = np.arange(9).reshape(3,3)
arr = arr[:,[2,1,0]]
arr

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

17. How to swap two rows in a 2d numpy array?

In [45]:
arr = np.arange(9).reshape(3,3)
arr = arr[[2,1,0],:]
arr

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

18. How to reverse the rows and columns of a 2D array?

In [48]:
arr = np.arange(9).reshape(3,3)
print arr[::-1]
print arr[:,::-1]

[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


20. How to create a 2D array containing random floats between 5 and 10?

In [51]:
arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print arr
print np.random.uniform(5,10,size=(5,3))

[[ 7.82072865  7.72806347  5.97818634]
 [ 6.71278168  6.85993377  9.71424292]
 [ 9.8100845   5.94354235  5.06483075]
 [ 6.25863435  9.78070939  8.21277059]
 [ 9.15562674  6.78294093  7.40482925]]
[[ 8.18803293  5.86580729  8.78147853]
 [ 6.61084228  5.48767727  6.94839556]
 [ 7.15976115  8.96553141  7.86767675]
 [ 5.50383899  5.46042024  9.99746441]
 [ 9.73789002  8.5943421   6.316365  ]]


21. How to print only 3 decimal places in python numpy array?

In [55]:
arr = np.random.random((5,3))
np.set_printoptions(precision=3)
arr

array([[ 0.864,  0.288,  0.852],
       [ 0.47 ,  0.811,  0.71 ],
       [ 0.334,  0.409,  0.889],
       [ 0.279,  0.927,  0.964],
       [ 0.295,  0.521,  0.398]])

In [60]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print rand_arr
np.set_printoptions(suppress=True, precision=6)
rand_arr

[[ 0.001  0.     0.   ]
 [ 0.001  0.     0.   ]
 [ 0.001  0.001  0.   ]]


array([[ 0.000543,  0.000278,  0.000425],
       [ 0.000845,  0.000005,  0.000122],
       [ 0.000671,  0.000826,  0.000137]])

23. How to limit the number of items printed in output of numpy array?

In [61]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [62]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa']], dtype=object)

26. How to extract a particular column from 1D array of tuples?

In [69]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print np.array([row[4] for row in iris_1d])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' ..., 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica']


27. How to convert a 1d array of tuples to a 2d numpy array?

In [71]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

28. How to compute the mean, median, standard deviation of a numpy array?

In [72]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris_length = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mu, med, std = np.mean(iris_length), np.median(iris_length), np.std(iris_length)
print mu, med, std

5.84333333333 5.8 0.825301291785


29. How to normalize an array so the values range exactly between 0 and 1?

In [74]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_length = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
smax = iris_length.max()
smin = iris_length.min()
iris_norm = (iris_length - smin) / (smax-smin)
print iris_norm

[ 0.222222  0.166667  0.111111 ...,  0.611111  0.527778  0.444444]


30. How to compute the softmax score?

In [75]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
s = np.exp(sepallength) / np.exp(sepallength).sum()
s

array([ 0.00222 ,  0.001817,  0.001488, ...,  0.009001,  0.006668,  0.00494 ])

31. How to find the percentile scores of a numpy array?

In [86]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sl = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sl.sort()
print sl[int(0.05 * len(sl))]
print sl[int(0.95 * len(sl))]
np.percentile(sl, q=[5, 95])

4.6
7.3


array([ 4.6  ,  7.255])

32. How to insert values at random positions in an array?

In [92]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
iris_2d[np.random.randint(150,size=20), np.random.randint(4, size=20)] = np.nan
print iris_2d[:30]

[['5.1' '3.5' nan '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ..., 
 ['5.2' '3.5' '1.5' '0.2' 'Iris-setosa']
 ['5.2' '3.4' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.6' '0.2' 'Iris-setosa']]


33. How to find the position of missing values in numpy array?

In [98]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
np.where(np.isnan(iris_2d[:,0]))


(array([ 0, 27, 39, 47]),)

34. How to filter a numpy array based on two or more conditions?

In [111]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
#condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
#iris_2d[condition]
c1 = iris_2d[0,:] > 3
c2 = iris_2d[1,:] > 4
print c1, c2
print iris_2d[:,c1&c2]

[ True  True False False] [ True False False False]
[[ 5.1]
 [ 4.9]
 [ 4.7]
 ..., 
 [ 6.5]
 [ 6.2]
 [ 5.9]]


35. How to drop rows that contain a missing value from a numpy array?

In [115]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

condition = np.where(np.isnan(iris_2d))
len(iris_2d[condition])

20

36. How to find the correlation between two columns of a numpy array?

In [118]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris[:, 0], iris[:, 2])


array([[ 1.      ,  0.871754],
       [ 0.871754,  1.      ]])

37. How to find if a given array has any null values?

In [119]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()

False

38. How to replace all missing values with 0 in a numpy array?

In [120]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[np.isnan(iris_2d)] = 0
print iris_2d[:4]

[[ 5.1  3.5  1.4  0.2]
 [ 0.   3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]]


In [121]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# Extract the species column as an array
species = np.array([row.tolist()[4] for row in iris])

# Get the unique values and the counts
np.unique(species, return_counts=True)

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], 
       dtype='|S15'), array([50, 50, 50]))

In [122]:
iris

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ..., 
       ['6.5', '3.0', '5.2', '2.0', 'Iris-virginica'],
       ['6.2', '3.4', '5.4', '2.3', 'Iris-virginica'],
       ['5.9', '3.0', '5.1', '1.8', 'Iris-virginica']], dtype=object)

40. How to convert a numeric to a categorical (text) array?

In [123]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [128]:
iris[:,2].astype('float')

array([ 1.4,  1.4,  1.3, ...,  5.2,  5.4,  5.1])

In [130]:
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])
# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:4]

['small', 'small', 'small', 'small']

41. How to create a new column from existing columns of a numpy array?

In [8]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
s = iris_2d[:,0].astype('float')
p = iris_2d[:,2].astype('float')
volume = (np.pi * p * (s**2))/3
volume = volume[:,np.newaxis]
print volume.shape , iris_2d.shape
out = np.hstack([iris_2d,volume])
out[:4]

(150, 1) (150, 5)


array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa', 38.13265162927291],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa', 35.200498485922445],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa', 30.0723720777127],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa', 33.238050274980004]], dtype=object)

42. How to do probabilistic sampling in numpy?

In [10]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
# Get the species column
species = iris[:, 4]
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object), array([77, 37, 36]))


In [12]:
index

array([ 59,  28,  42, 119,   1,  12,  84, 115,  14,  65, 128,  21,  19,
        11,  22, 145, 112,  17, 113,  27,  43, 138, 114,  33,  18,  37,
         1,  25, 109,   2,  70,  71,  11,  38,   4, 128, 146,   6, 128,
        65,  98,  76,  66,   3,  21,  59, 104,  25,  29, 120, 145, 127,
        36,  70,  35,  34,  18,  24,   5,  51,  37,  69,  76,  14, 136,
       139,  70,  39,  36,  21,  28,  25,  18, 143, 141,  70,  96,  34,
        10,  46,  52,   9,  56, 148,  39,  33, 111, 101,  31,  77,  58,
        30,  11,  31,  45,  82,  25,  78,  20,  81, 106, 106,  72,  31,
        89, 122,  75, 146, 145,  17,   3,  16, 134, 140,  21,  36,  60,
        27,  46,  89,  50,  93,  55,   1,  39,  49,  40,  35,  50,  44,
         9,  27, 138,   3,   4,  28,  67, 148, 148, 148,  11,  83,  55,
        17, 138,  24, 149,  67,  18,  38])

In [1]:
import logging

In [2]:
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s',
                    datefmt='%a, %d %b %Y %H:%M:%S',
                    filename='myapp.log',
                    filemode='w')


In [4]:
logging.debug('This is debug message')
logging.info('This is info message')


44. How to sort a 2D array by a column

In [7]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[iris[:,0].argsort()][:20]

array([['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.4', '3.0', '1.3', '0.2', 'Iris-setosa'],
       ['4.4', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.5', '2.3', '1.3', '0.3', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['4.6', '3.6', '1.0', '0.2', 'Iris-setosa'],
       ['4.6', '3.2', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.8', '3.4', '1.9', '0.2', 'Iris-setosa'],
       ['4.8', '3.1', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.3', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['4.9

45. How to find the most frequent value in a numpy array?